
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'home/$', 'present_trip.views.home'),
    url(r'home/(\w+)/$' , 'present_trip.views.home'),
    url(r'help/$', 'tourism.views.help'),
    url(r'cancelselling/(\w+)$','define_and_validate_trip.views.cancel'),
    url(r'tourdefine/(\w+)$', 'define_and_validate_trip.views.tarif_kind'),
    url(r'tourdefine/tour/(\w+)$','define_and_validate_trip.views.tour_define'),
    url(r'tourdefine/tour/change/(\w+)$','define_and_validate_trip.views.tour_define'),
    url(r'tourdefine/airplane/(\w+)$','define_and_validate_trip.views.airplane_define'),
    url(r'tourdefine/train/(\w+)$','define_and_validate_trip.views.train_define'),
    url(r'signup/$', 'user.views.signup'),
    url(r'signIn/$', 'user.views.signin'),
    url(r'forgetpassword/$', 'user.views.forget_password'),
    url(r'signup/tourist/(\w+)$', 'user.views.tourist_signup'),
    url(r'signup/tourBuilder/(\w+)$', 'user.views.servant_signup'),
    url(r'editprofile/tourist/(\w+)$','user.views.edit_tourist'),
    url(r'profile/tourist/(\w+)$','user.views.tourist_profile'),
    url(r'profile/tourbuilder/(\w+)$','user.views.tourbuilder_profile'),
    url(r'editprofile/tourbuilder/(\w+)$','user.views.edit_tourbuilder'),
    url(r'userpage/(\w+)$', 'informing.views.account'),
    url(r'show/(\w+)/$', 'present_trip.views.show_one_trip'),
    url(r'show/(\w+)/(\w+)$', 'present_trip.views.show_one_trip'),
    url(r'show/(\w+)/(\w+)/status/$', 'present_trip.views.show_one_trip_status'),
   # url(r'reserve/(P?<tour_id>\d+)/$', 'buy_cancel.views.reserve'),

     url(r'reserve/(\w+)/$', 'buy_cancel.views.reserve'),
   #  url(r'reserve/([service][tour])/$', 'buy_cancel.views.reserve'),
   url(r'purchase/(P?<tour_id>\d+)/$', 'buy_cancel.views.purchase'),
     url(r'purchase/(\w+)/$', 'buy_cancel.views.purchase'),
     url(r'purchase/$', 'buy_cancel.views.purchase'),
    url(r'search/form/$', 'present_trip.views.start_search'),
    url(r'search/form/(\w+)/$', 'present_trip.views.start_search'),
    url(r'search/result/$', 'present_trip.views.search'),
    url(r'search/result/(\w+)/$', 'present_trip.views.search'),
    url(r'search/result/(\w+)/(\w+)$', 'present_trip.views.search'),
    url(r'purchase/(P?<tour_id>\d+)/$', 'buy_cancel.views.purchase'),
    url(r'cancel/(\w+)/$', 'accounting.views.cancel'),
    url(r'payment/(P?<id>\d+)/$', 'accounting.views.payment'),
    url(r'payment/Confirm/(P?<id>\d+)/$', 'accounting.views.confirm'),
    url(r'payment/$', 'accounting.views.payment'),
    url(r'payment/confirm/(P?<id>\d+)/$', 'accounting.views.confirm'),
     url(r'payment/confirm/$', 'accounting.views.confirm'),
     url(r'manager/Dashboard/$', 'manager_dashboard.views.Dashboard'),
    url(r'manager/tourLists/$', 'manager_dashboard.views.tourLists'),
    url(r'manager/tourRating/$', 'manager_dashboard.views.tourRating'),
    url(r'manager/tourRating/$', 'manager_dashboard.views.onlineComments'),
    url(r'manager/userLists/$', 'manager_dashboard.views.userLists'),
    url(r'manager/paymentsList/$', 'manager_dashboard.views.paymentLists'),
    url(r'manager/OnlineComments/$', 'manager_dashboard.views.onlineComments'),
    url(r'polling/(P?<tour_id>\+d)/$', 'quality_control.views.polling'),
    url(r'onlinePolling/$', 'quality_control.views.onlinePolling'),
    url(r'^admin/', include(admin.site.urls)),
]
